CREATE TABLE IF NOT EXISTS  "Categories" (
          "Category_Code" integer GENERATED BY DEFAULT AS IDENTITY,
          "Category_Name" text NOT NULL,
          "Category_Creation_Date" timestamp with time zone NOT NULL,
          CONSTRAINT "PK_Categories" PRIMARY KEY ("Category_Code")
      );

CREATE TABLE IF NOT EXISTS "Products" (
          "Product_Code" integer GENERATED BY DEFAULT AS IDENTITY,
          "Product_Name" text NOT NULL,
          "Product_Category_Code" integer NOT NULL,
          "Product_Creation_Date" timestamp with time zone NOT NULL,
          CONSTRAINT "PK_Products" PRIMARY KEY ("Product_Code")
      );